### ISSUE TITLE
Error while doing "bundle exec jekyll serv"

### ISSUE THREAD

**Issue by ghost** [sharadcodes/jekyll-theme-material-you#3]
Hey, im a beginner in all this! and want to add this theme. buuut. i tried running the command in the title
and it gave me an error:
  Liquid Exception: undefined method `tainted?' for "Jekyll Material You":String in C:/Users/hello/jekyll-theme-material-you/_layouts/post.html
                    ------------------------------------------------
      Jekyll 4.2.2   Please append `--trace` to the `serve` command
                     for any additional information or backtrace.
                    ------------------------------------------------
how do i fix this?

another question:

what do you mean by "Access via
localhost or according to your pc configurations." ???

please help!

**Comment by sharadcodes** [comment]
Hi @TeaEndsAcronyms , 
Looks like there is some problem, run  `bundle exec jekyll serve --trace`  and share the output if you can.

BY
Access via localhost or according to your pc configurations
I mean to say that some people use IP address instead of localhost so that's completely up to them.

**Comment by ghost** [comment]
This is what happened when i did "bundle exec jekyll serve --trace":


Configuration file: C:/Users/hello/jekyll-theme-material-you/_config.yml
            Source: C:/Users/hello/jekyll-theme-material-you
       Destination: C:/Users/hello/jekyll-theme-material-you/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
       Jekyll Feed: Generating feed for posts
  Liquid Exception: undefined method `tainted?' for "Jekyll Material You":String in C:/Users/hello/jekyll-theme-material-you/_layouts/post.html
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/liquid-4.0.3/lib/liquid/variable.rb:124:in `taint_check': undefined method `tainted?' for "Jekyll Material You":String (NoMethodError)

      return unless obj.tainted?
                       ^^^^^^^^^
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/liquid-4.0.3/lib/liquid/variable.rb:89:in `render'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/liquid-4.0.3/lib/liquid/block_body.rb:103:in `render_node_to_output'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/liquid-4.0.3/lib/liquid/block_body.rb:80:in `render'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/liquid-4.0.3/lib/liquid/template.rb:208:in `block in render'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/liquid-4.0.3/lib/liquid/template.rb:242:in `with_profiling'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/liquid-4.0.3/lib/liquid/template.rb:207:in `render'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/liquid-4.0.3/lib/liquid/template.rb:220:in `render!'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.2.2/lib/jekyll/liquid_renderer/file.rb:39:in `block (3 levels) in render!'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.2.2/lib/jekyll/liquid_renderer/file.rb:59:in `measure_counts'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.2.2/lib/jekyll/liquid_renderer/file.rb:38:in `block (2 levels) in render!'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.2.2/lib/jekyll/liquid_renderer/file.rb:63:in `measure_bytes'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.2.2/lib/jekyll/liquid_renderer/file.rb:37:in `block in render!'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.2.2/lib/jekyll/liquid_renderer/file.rb:70:in `measure_time'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.2.2/lib/jekyll/liquid_renderer/file.rb:36:in `render!'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.2.2/lib/jekyll/inclusion.rb:16:in `render'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.2.2/lib/jekyll/tags/include.rb:208:in `block in render'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/liquid-4.0.3/lib/liquid/context.rb:123:in `stack'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.2.2/lib/jekyll/tags/include.rb:206:in `render'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/liquid-4.0.3/lib/liquid/block_body.rb:103:in `render_node_to_output'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/liquid-4.0.3/lib/liquid/block_body.rb:91:in `render'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/liquid-4.0.3/lib/liquid/template.rb:208:in `block in render'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/liquid-4.0.3/lib/liquid/template.rb:242:in `with_profiling'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/liquid-4.0.3/lib/liquid/template.rb:207:in `render'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/liquid-4.0.3/lib/liquid/template.rb:220:in `render!'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.2.2/lib/jekyll/liquid_renderer/file.rb:39:in `block (3 levels) in render!'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.2.2/lib/jekyll/liquid_renderer/file.rb:59:in `measure_counts'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.2.2/lib/jekyll/liquid_renderer/file.rb:38:in `block (2 levels) in render!'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.2.2/lib/jekyll/liquid_renderer/file.rb:63:in `measure_bytes'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.2.2/lib/jekyll/liquid_renderer/file.rb:37:in `block in render!'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.2.2/lib/jekyll/liquid_renderer/file.rb:70:in `measure_time'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.2.2/lib/jekyll/liquid_renderer/file.rb:36:in `render!'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.2.2/lib/jekyll/renderer.rb:131:in `render_liquid'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.2.2/lib/jekyll/renderer.rb:194:in `render_layout'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.2.2/lib/jekyll/renderer.rb:163:in `place_in_layouts'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.2.2/lib/jekyll/renderer.rb:93:in `render_document'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.2.2/lib/jekyll/renderer.rb:63:in `run'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.2.2/lib/jekyll/site.rb:547:in `render_regenerated'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.2.2/lib/jekyll/site.rb:532:in `block (2 levels) in render_docs'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.2.2/lib/jekyll/site.rb:531:in `each'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.2.2/lib/jekyll/site.rb:531:in `block in render_docs'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.2.2/lib/jekyll/site.rb:530:in `each_value'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.2.2/lib/jekyll/site.rb:530:in `render_docs'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.2.2/lib/jekyll/site.rb:210:in `render'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.2.2/lib/jekyll/site.rb:80:in `process'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.2.2/lib/jekyll/command.rb:28:in `process_site'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.2.2/lib/jekyll/commands/build.rb:65:in `build'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.2.2/lib/jekyll/commands/build.rb:36:in `process'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.2.2/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.2.2/lib/jekyll/command.rb:91:in `each'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.2.2/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.2.2/lib/jekyll/commands/serve.rb:86:in `block (2 levels) in init_with_program'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.2.2/exe/jekyll:15:in `<top (required)>'
        from C:/Ruby32-x64/bin/jekyll:32:in `load'
        from C:/Ruby32-x64/bin/jekyll:32:in `<main>'


hope this helps!

**Comment by sharadcodes** [comment]
Can you delete the gemfile.lock and try building again

**Comment by ghost** [comment]
Tried that. no luck, just gave me the same output as before...

**Comment by sharadcodes** [comment]
Try this Gemfile

https://github.com/actions/jekyll-build-pages/blob/main/Gemfile

Just replace the one in the repo with this

**Comment by sharadcodes** [comment]
I've this version of ruby

`ruby 3.1.3p185 (2022-11-24 revision 1a6b16756e) [x64-mingw-ucrt]`

**Comment by sharadcodes** [comment]
Did you change anything in the code ?

**Comment by TeaEndsAcronyms** [comment]
Nope. Simply git cloned it, and I'm using [ruby 3.2.0](https://rubyinstaller.org/) (the installer for windows)

**Comment by TeaEndsAcronyms** [comment]
Nope. Simply git cloned it, and I'm using [ruby 3.2.2](https://rubyinstaller.org/) (the installer for windows)

**Comment by ghost** [comment]
> Did you change anything in the code ?

Nope. Simply git cloned it, and I'm using [ruby 3.2.2](https://rubyinstaller.org/) (the installer for windows)

**Comment by sharadcodes** [comment]
Okay, try using old one, or use github codespace. I think it should fix it

**Comment by ghost** [comment]
i tried github codespace. while doing "bundle install"
it shows an error: An error occurred while installing racc (1.6.2), and Bundler cannot
continue.

**Comment by TeaEndsAcronyms** [comment]
also tried downgrading to ruby 3.0.6 and that made it so bundle is not even a command...

**Comment by ghost** [comment]
Downgrading to ruby 3.0.6 made it work!

**Comment by ghost** [comment]
also what files should u upload to my repository? all of them or just config.yml, gemfile and author.yml

**Comment by sharadcodes** [comment]
> also what files should u upload to my repository? all of them or just config.yml, gemfile and author.yml

All files should be uploaded, if you add ruby specific or jekyll specific gitignore it will do the job

**Comment by sharadcodes** [comment]
> Downgrading to ruby 3.0.6 made it work!

Great
