### ISSUE TITLE
How to i make the theme on my Markdown (readme.md)?

### ISSUE THREAD

**Issue by ghost** [sharadcodes/jekyll-theme-material-you#4]
Hey, its me again! i just wanted to ask. i dont have experience at all in html, and im assuming it uses that? im wondering on how to use my readme.md to add text (for my github pages) instead of html... 

help me!

**Comment by sharadcodes** [comment]
Can you please explain what you want to achieve ?  I may be late in response so apologies for that, there is  a time zone difference as well.

**Comment by sharadcodes** [comment]
I assume you want to use only md files and no html ? Am I right ?

**Comment by ghost** [comment]
Yeah. Exactly!

**Comment by ghost** [comment]
Hey, its been 2 days... Any chance you could still help me with this issue?

**Comment by sharadcodes** [comment]
That is not possible since you do have to add css and other meta tags to it, apologies for the late response

**Comment by ghost** [comment]
all right i guess!
