### ISSUE TITLE
How to make a second blog/section?

### ISSUE THREAD

**Issue by ghost** [sharadcodes/jekyll-theme-material-you#5]
hey i ended up learning html (i had dedication) and made a section that im very proud of! but...
 im wondering how you make it so you have 2+
For exmaple "jekyll markdown" **AND** "the purpose of education" (or whatever the hell the default title was lol)
whenever i try to make two the second one doesnt show up?

sorry for making so many issues lol (hopefully the final one)
 i just really like this theme!

**Comment by sharadcodes** [comment]
I'm glad that you liked the theme  and kudos to you for your efforts.

As for the problem can you tell the dir structure of your project

**Comment by sharadcodes** [comment]
It must be due to some file error

**Comment by ghost** [comment]
Fixed it myself :) issue closed.
